name: Invoke from other repo

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
        

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.tag=='runbuild' }}
    steps:      
      - uses: actions/checkout@v2
      - run: echo "Hello pavan its me from same repo but reuse1 branch other repo ${{inputs.image_name}}"
     
          
  do-something-else:
    runs-on: ubuntu-latest
    if: ${{ inputs.tag=='runelse' }}
    steps:
    - run: echo "Hello"
