name: workflow_reuse

on:
  workflow_dispatch:

jobs:
  reusejob:
    call-workflow:
      permissions:
        contents: read
        pull-requests: write
      uses: "kpnssreeram/reuseworkflow/.github/workflows/h1.yml@main"
      with:
         name: hello