name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: kpnssreeram/resuseworkflow/.github/workflows/reuses.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: octo-org/example-repo/.github/workflows/h1.yml@resue1
    with:
      config-path: .github/labeler.yml
