# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world main repo!

  data_storage:
    uses: kpnssreeram/workflowtest/.github/workflows/A.yml@dev
    with:
      image_name: my-awesome-app
